### PR TITLE
Update to 3.0.2 from Richard Atterer <atterer@debian.org>. See README…

### PR DESCRIPTION
**Pull request by zosrothko**
Update to 3.0.2 from Richard Atterer atterer@debian.org. See READM.Debian.

Signed-off-by: FrancisANDRE zosrothko@orange.fr

### CODE REVIEW

**Comment by elfring** [comment]
- How does the request title fit to the version "3.0-5" [which is published by Debian packages](https://packages.debian.org/search?keywords=BtYacc&searchon=names&suite=all&section=all) at the moment?
- Are there any chances to integrate desired changes on a few topic branches individually (instead of a single commit)?

**Comment by zosrothko** [comment]
How does the request title fit to the version "3.0-5" which is published by Debian packages at the moment? No idea, Only the 3.0.2 for Debian is available from my view. Any way, IMO, one should merge this version and publishes it as 3.0.2 release

Are there any chances to integrate desired changes on a few topic branches individually (instead of a single commit)? You should create a develop branch in which all PRs will be cumulated at your convenience and make master protected. Also the develop branch should be default branch, not the master...

**Comment by elfring** [comment]
> No idea, Only the 3.0.2 for Debian is available from my view.

Would you like to refer to the version identifier "3.0-2" instead?

> You should create a develop branch …

I imagine that [some topic branches](https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows) could be useful. I am unsure on how many efforts I would like to invest for the synchronisation of this repository with software developments from other sources (like Debian).

**Comment by zosrothko** [comment]
Would you like to refer to the version identifier "3.0-2" instead? Ok no problem

I imagine that some topic branches could be useful. I am unsure on how many efforts I would like to invest for the synchronisation of this repository with software developments from other sources (like Debian).AS owner of this public repository, it is your duty and responsability to synchronize all PRs to the master branch

**Comment by elfring** [comment]
I did not update this repository for years. I guess that it will take another while till I'll become a bit more interested in corresponding software development again.

**Comment by zosrothko** [comment]
OK so could you transfer the ownership of this repository to me?

**Comment by elfring** [comment]
I do not see a need for such a transfer. You can continue software development on your own repositories as usual, can't you?

**Comment by zosrothko** [comment]
Someone has to manage improvments on the code base proposed by forkers into a single instance of the code, thath how collaborative works.. As you do not want to take in charge this job, I am proposing to do it...

**Comment by elfring** [comment]
One of the involved software development challenges is the selection of the appropriate source code base, isn't it?
- [Debian](https://packages.debian.org/search?keywords=BtYacc&searchon=names&suite=all&section=all)
- [My additions](https://github.com/elfring/BtYacc/commits/route1)
- [Siber Systems](http://www.siber.com/btyacc/)

**Comment by zosrothko** [comment]
The original code from Siber system should be the starting point.

1/ Siber system (i.e the current master, make a tag 3.0 from this point)
2/ Merge Debian into master and make a tag Debian 3.0-2
3/ create a new branch from master named develop
4/ Protect master
5/ Merge route1 into develop
6/ if the develop branch is ok for release, make a new tag and use a PR to update the master.
7/ From then, all new developments will be accumulated into the branch develop up to the point they will make a new release.

**Comment by elfring** [comment]
> … Merge Debian …

I suggest to [consider also the version "3.0-5+b2"](https://packages.debian.org/sid/btyacc) then.

> … Protect master …

Such an action would not be needed.

> … Merge route1 into develop …

I guess that [cherry-picking from my commits](https://git-scm.com/book/en/v2/Distributed-Git-Maintaining-a-Project#_rebase_cherry_pick) (and from other sources eventually) would be more useful on corresponding topic branches.

**Comment by zosrothko** [comment]
> suggest to consider also the version "3.0-5+b2" then.
> Sure...
> 
> I guess that cherry-picking from my commits (and from other sources eventually) would be more useful on corresponding topic branches.
> Not really..; what is important is to share all improvements from the various contributors into a single branch -- the develop branch -- so that it is easy with git to push this develop branch into each forks. That's the way, contributions can be propagated without effort... Once all changes you have made in route1 be merged into the develop branch, all forked repositories/branches can be updated easily with a single pull and continue their own development in their private branch.

So please, add a develop branch and merge all the route1 branch into, and make the develop branch the default branch for cloning.

You can also rename route1 to develop and that's it...

**Comment by elfring** [comment]
> Not really …

Would you like to try cherry-picking a bit more out for commits?

> … share all improvements from the various contributors into a single branch …

I suggest to increase topic branch usage. Patches can eventually be integrated into several branches.

> You can also rename route1 to develop …

My software development approach will not work in this way. Are you going to experiment with other approaches in your repositories?

**Comment by zosrothko** [comment]
Ok I give up... and will switch to the original Chris Dodd btyacc which has already differences with the one from Syber

**Comment by elfring** [comment]
> Ok I give up …

Software development will be continued by other interfaces then. I am curious if further progress can still be achieved for the involved issues somehow.

**Comment by zosrothko** [comment]
Workign on btyacc with the original author seems a good point

https://github.com/ChrisDodd/btyacc

**Comment by elfring** [comment]
I am curious on how many software improvements can be achieved together with [Chris Dodd](https://github.com/ChrisDodd/btyacc) then.

**Comment by zosrothko** [comment]
BTW, replacing int by size_t to avoid the warning of comparison between an signed/unsigned quantity is sometime not a good idea.

This statement is looping with size_t j:        while (--j >= 0) BtYacc_putc(' ', f);

**Pull request closed without merging**
